version: "3"
services:
  dbserver:
    image: postgres:9.6
    hostname: dbserver
    container_name: dbserver
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cruddb
