version: "3"
services:
  database:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_DATABASE: cruddb
    ports:
      - 3300:3300
