spring:
  datasource:
    sqlScriptEncoding: UTF-8
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cruddb?useSSL=false&requireSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    sql: debug